spring:
  shardingsphere:
    datasource:
      names: master1,slave1,slave2  #指定所有数据源的名字
      master1:
        type: com.zaxxer.hikari.HikariDataSource #数据源类型
        url: jdbc:mysql://192.168.136.130:3306/gmall_product?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

      slave1:
        type: com.zaxxer.hikari.HikariDataSource #数据源类型
        url: jdbc:mysql://192.168.136.130:3307/gmall_product?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

      slave2:
        type: com.zaxxer.hikari.HikariDataSource #数据源类型
        url: jdbc:mysql://192.168.136.130:3308/gmall_product?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    rules:
      readwrite-splitting:  #配置读写分离规则
        data-sources:
          ds_0:   #给一套集群起个名
            type: static
            props:
              auto-aware-data-source-name: master1
              write-data-source-name: master1
              read-data-source-names: slave1,slave2
            load-balancer-name: read-random
        load-balancers:
          read-random:
            type: ROUND_ROBIN #轮询负载均衡
    props:
      sql-show: true
      sql-simple: true