server:
  port: 7000

#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.136.130:3306/gmall_product?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

app:
  minio:
    endpoint: http://192.168.136.130:9000
    accessKey: admin
    secretKey: admin123456
    bucket: gmall
